import { Readable } from 'node:stream';

import type { drive_v3 } from 'googleapis';

import type { IDriveRepository } from '../interfaces/drive-repository.interface.js';
import type { DriveFile } from '../models/drive-file.model.js';
import type { ListFilesParams } from '../models/list-params.model.js';
import type { ListRecordingsParams } from '../models/list-recordings-params.model.js';
import type { SearchParams } from '../models/search-params.model.js';
import type { UploadParams } from '../models/upload-params.model.js';
import { FileNotFoundError } from '../errors/file-not-found.error.js';
import { TranscriptNotFoundError } from '../errors/transcript-not-found.error.js';
import { UploadError } from '../errors/upload.error.js';
import { mapToDriveFile } from './drive.mapper.js';

const FILE_FIELDS = 'id,name,mimeType,size,modifiedTime,parents';
const LIST_FIELDS = `files(${FILE_FIELDS}),nextPageToken`;

// Maps Google Workspace MIME types to a plain-text export format
const EXPORT_MIME_MAP: Record<string, string> = {
  'application/vnd.google-apps.document': 'text/plain',
  'application/vnd.google-apps.spreadsheet': 'text/csv',
  'application/vnd.google-apps.presentation': 'text/plain',
};

// Audio and video MIME types that represent meeting recordings
const RECORDING_MIME_TYPES = [
  'video/mp4',
  'video/webm',
  'video/quicktime',
  'video/x-msvideo',
  'audio/mpeg',
  'audio/wav',
  'audio/ogg',
  'audio/mp4',
  'audio/x-m4a',
];

export class DriveRepository implements IDriveRepository {
  constructor(private readonly client: drive_v3.Drive) {}

  async listFiles(params: ListFilesParams): Promise<DriveFile[]> {
    const conditions: string[] = ['trashed = false'];

    if (params.folderId !== undefined) {
      conditions.push(`'${params.folderId}' in parents`);
    }
    if (params.mimeType !== undefined) {
      conditions.push(`mimeType = '${params.mimeType}'`);
    }

    const res = await this.client.files.list({
      q: conditions.join(' and '),
      pageSize: params.pageSize,
      fields: LIST_FIELDS,
    });

    return (res.data.files ?? []).map(mapToDriveFile);
  }

  async getFileContent(fileId: string): Promise<Buffer> {
    const meta = await this.client.files.get({ fileId, fields: 'mimeType' });
    const mimeType = meta.data.mimeType ?? '';

    if (mimeType.startsWith('application/vnd.google-apps.')) {
      // Google Workspace files must be exported, not downloaded directly
      const exportMime = EXPORT_MIME_MAP[mimeType] ?? 'text/plain';
      const res = await this.client.files.export(
        { fileId, mimeType: exportMime },
        { responseType: 'arraybuffer' }
      );
      return Buffer.from(res.data as ArrayBuffer);
    }

    const res = await this.client.files.get(
      { fileId, alt: 'media' },
      { responseType: 'arraybuffer' }
    );

    if (res.data == null) {
      throw new FileNotFoundError(fileId);
    }

    return Buffer.from(res.data as ArrayBuffer);
  }

  async uploadFile(params: UploadParams): Promise<DriveFile> {
    const metadata: drive_v3.Schema$File = { name: params.name };

    if (params.folderId !== undefined) {
      metadata.parents = [params.folderId];
    }

    const res = await this.client.files.create({
      requestBody: metadata,
      media: {
        mimeType: params.mimeType,
        body: Readable.from(params.content),
      },
      fields: FILE_FIELDS,
    });

    if (res.data == null) {
      throw new UploadError(`Upload failed for file: ${params.name}`);
    }

    return mapToDriveFile(res.data);
  }

  async searchFiles(params: SearchParams): Promise<DriveFile[]> {
    const res = await this.client.files.list({
      q: `(${params.query}) and trashed = false`,
      pageSize: params.pageSize,
      fields: LIST_FIELDS,
    });

    return (res.data.files ?? []).map(mapToDriveFile);
  }

  async getFileMimeType(fileId: string): Promise<string> {
    const res = await this.client.files.get({ fileId, fields: 'mimeType' });
    return res.data.mimeType ?? '';
  }

  async listRecordings(params: ListRecordingsParams): Promise<DriveFile[]> {
    const mimeConditions = RECORDING_MIME_TYPES.map((t) => `mimeType = '${t}'`).join(' or ');
    const conditions = [`(${mimeConditions})`, 'trashed = false'];

    if (params.folderId !== undefined) {
      conditions.push(`'${params.folderId}' in parents`);
    }

    const res = await this.client.files.list({
      q: conditions.join(' and '),
      pageSize: params.pageSize,
      fields: LIST_FIELDS,
    });

    return (res.data.files ?? []).map(mapToDriveFile);
  }

  async findTranscript(recordingFileId: string): Promise<DriveFile> {
    const meta = await this.client.files.get({
      fileId: recordingFileId,
      fields: 'parents',
    });

    const parentId = meta.data.parents?.[0];
    if (parentId === undefined) {
      throw new TranscriptNotFoundError(recordingFileId);
    }

    // VTT files are the default transcript format generated by Google Meet
    const vttRes = await this.client.files.list({
      q: `'${parentId}' in parents and mimeType = 'text/vtt' and trashed = false`,
      pageSize: 10,
      fields: LIST_FIELDS,
    });

    const firstVtt = (vttRes.data.files ?? [])[0];
    if (firstVtt !== undefined) {
      return mapToDriveFile(firstVtt);
    }

    // Fallback: Google Docs with "Transcript" in the name (some Meet configs use this)
    const docRes = await this.client.files.list({
      q: `'${parentId}' in parents and mimeType = 'application/vnd.google-apps.document' and name contains 'Transcript' and trashed = false`,
      pageSize: 10,
      fields: LIST_FIELDS,
    });

    const firstDoc = (docRes.data.files ?? [])[0];
    if (firstDoc !== undefined) {
      return mapToDriveFile(firstDoc);
    }

    throw new TranscriptNotFoundError(recordingFileId);
  }

  async deleteFile(fileId: string): Promise<void> {
    await this.client.files.delete({ fileId });
  }
}
